### ISSUE TITLE
able to scroll

### ISSUE THREAD

**Issue by trwww** [anseki/plain-modal#1]
Hello, I tried this out on my older machine and the overlaid window could not scroll - all worked as expected. But when I tried on my newer Mac, same up-to-date version of Chrome, I found the overlaid window could scroll, and the elements were not clickable where they were displayed. See in attached gif where you can see the window scrolled and I can click to close the overlay far below where the button displays.

In firefox I can scroll while the overlay loads, but it does finally lock a few seconds later right after the blur is activated.

![able-to-scroll](https://user-images.githubusercontent.com/216991/41192810-da5f9da6-6bd1-11e8-87fd-715ceed32c8c.gif)

**Comment by anseki** [comment]
Hi @trwww, thank you for the report.
I have no idea about that behavior...
I tried the example in Google Chrome v67.0.3396.79 but I could not reproduce that.

So, does that occur when you click other buttons?
And, does the console show any error or something?
Does reloading solve that?

**Comment by trwww** [comment]
Gah sorry the chrome version was about 6 months old. I thought for sure I was up to date. Its working fine on the latest version.

**Comment by anseki** [comment]
I see. :smile: 
The current Chrome and that of 6 months ago are almost the same. And, PlainModal of course supports both.
It seems that the Chrome and Firefox in you computer were broken.
