### ISSUE TITLE
Issue with duration 0

### ISSUE THREAD

**Issue by MathieuRoger** [anseki/plain-modal#13]
When setting duration:0; after close, the modal div is stil partly ther in front, preventing from interacting with the normal page.
Typically it does not have the 'plainoverlay-hide' class.

**Comment by anseki** [comment]
Hi @MathieuRoger, thank you for the comment.
Do you mean that a part of contents in a modal was being shown after the modal was closed?
Could you show an example by using e.g. https://jsfiddle.net/ to reproduce that?

**Comment by MathieuRoger** [comment]
https://jsfiddle.net/tmdo1q02/1/
1. click on red main : nothing
2. change duration to 1
3. click on red main : alert is triggered

In fact, 
* when duration = 0, the modal div has been modified to
<div class="plainoverlay plainoverlay-doc plainmodal" style="transition-duration: 0ms;"><div class="plainoverlay-body"><div id="modal-content" style="display: block; background-color: green;" class="plainmodal-content">
    Hello world
  </div><div class="plainmodal-overlay plainmodal-overlay-force"></div></div></div>
* when duration = 1, the modal div has been modfiedto
<div class="plainoverlay plainoverlay-doc plainmodal plainoverlay-hide" style="transition-duration: 1ms;"><div class="plainoverlay-body"><div id="modal-content" style="display: block; background-color: green;" class="plainmodal-content">
    Hello world
  </div><div class="plainmodal-overlay plainmodal-overlay-force"></div></div></div>

In the case duration:0 the 'plainoverlay-hide' class is missing...

**Comment by anseki** [comment]
I see.
Some browsers might skip event when the `duration` is `0`.
Specify `1` for that or specify `true` for `force` argument of `open` or `close` method instead.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
