### ISSUE TITLE
PlainModal.closeByOverlay undefined

### ISSUE THREAD

**Issue by butachan** [anseki/plain-modal#21]
Hi I can't figure out the syntax to prevent the modal from closing when clicking outside,

According to the docs:  set PlainModal.closeByOverlay = false to disable this behavior.

my modal is defined as : 
` var modal = $('#shipment-modal').plainModal()`
and it works

To dsable the default overlay click, here are my attempts :

`
modal.plainModal.closeByOverlay=false;
modal.closeByOverlay=false;
PlainModal.closeByOverlay = false;
$('#shipment-modal').plainModal.closeByOverlay=false;
`

I tried each one of these inside the var modal declaration, outside and in documentready. None of these work.

By the way there is no 'closeByOverlay' keyword found in my project.

I need help, pls

**Comment by anseki** [comment]
Hi @butachan, thank you for the comment.
You seem to have mistaken a repository that you should ask the question to. You are talking about a jQuery Plugin or something. This is a repository of PlainModal (Not jQuery Plugin).
The document is here: https://anseki.github.io/plain-modal/

**Comment by butachan** [comment]
Hi, OK my bad

**Comment by butachan** [comment]
jquery plainModal =/= PlainModal
