### ISSUE TITLE
Need Help.

### ISSUE THREAD

**Issue by bubbsJanko** [anseki/plain-modal#23]
Hi I want to say your projects are amazing and you do a great job. I am pretty new to js but understand the basics. I was wondering if you would be able to help me with something, if so that would be greatly appreciated! For your leader-line project how would it be possible for me to get the leader-line.min.js but without the minification. I want to analyze and play with parts of the code but it is impossible for me to read. How would I go about doing this I know you have all of the source code available and I have tried things but no luck. Thanks for taking the time to read this and if you are able to help that would be awesome. Thankyou.

**Comment by anseki** [comment]
Hi @bubbsJanko, thank you for the comment.
All files of LeaderLine project are open to the public on the project repository: https://github.com/anseki/leader-line
You can download those files including source code that is not minified from the repository.
Not here. This is "PlainModal" repository.

**Comment by bubbsJanko** [comment]
Thanks for the response. The reason why I am messaging you on "PlainModal" is because I was unable to open an issue on "leader-line" as it is read only. I understand that I can clone the repository but then what would I have to do from there. I have tried creating an "index.html" in the src folder and linking the .js files in there but that did not work. I guess what I am asking is once the repository is cloned what do I do from there. Again thank you so much for taking the time to respond I really appreciate it thanks.

**Comment by anseki** [comment]
Sorry, I don't know what you want to do.
If you want to read the source code that was not minified, you can do that without creating the HTML file in the directory.
If you want to customize that, you can read build-script in the repository.
If you want to run the library, you have to create a HTML file and load `leader-line.min.js` that was builded. Not another file in the `src` directory.

**Comment by bubbsJanko** [comment]
Sorry if I am making this confusing. 
Question: Is it Gruntfile.js which is minifying the source code?
Also: What I am trying to say is there any way to run the library without loading the minified version? Is there a way to build a new file which is not minified and load that? I want to be able to change the source code of the leader-line.min.js but I cannot because it is minified. So is there a way to combine all the files from the src into a new file to be loaded that is not minified. That way I can easily play with the source code. Does that make sense?

**Comment by anseki** [comment]
You should learn [Grunt](https://gruntjs.com/) and JavaScript ecosystem.
Sorry, my English is poor. Therefore, you'd better read the document above, and you can get the source code that you want by writing a build script.

**Comment by bubbsJanko** [comment]
Doing some more research I was able to to find a solution thankyou so much for the help!

**Comment by anseki** [comment]
😄
